### ISSUE TITLE
All commands for rancher fail

### ISSUE THREAD

**Issue by VetheonGames** [Nutty101/NPCDestinations_Rancher#2]
all commands fail saying "invalid argument" in chat and this in console:

[15:52:48 INFO]: VetheonGames issued server command: /nd locrancher 0 ranch
[15:52:48 INFO]: nd
[15:52:48 WARN]: java.lang.reflect.InvocationTargetException
[15:52:48 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor409.invoke(Unknown Source)
[15:52:48 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:48 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[15:52:48 WARN]:        at NPC_Destinations-2_6_10.jar//net.livecar.nuttyworks.npc_destinations.listeners.commands.Command_Record.invokeCommand(Command_Record.java:49)
[15:52:48 WARN]:        at NPC_Destinations-2_6_10.jar//net.livecar.nuttyworks.npc_destinations.listeners.commands.Command_Manager.onCommand(Command_Manager.java:140)
[15:52:48 WARN]:        at NPC_Destinations-2_6_10.jar//net.livecar.nuttyworks.npc_destinations.DestinationsPlugin.onCommand(DestinationsPlugin.java:498)
[15:52:48 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:52:48 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:52:48 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[15:52:48 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2262)
[15:52:48 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[15:52:48 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[15:52:48 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[15:52:48 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[15:52:48 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[15:52:48 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:52:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[15:52:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[15:52:48 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[15:52:48 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[15:52:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[15:52:48 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[15:52:48 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[15:52:48 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[15:52:48 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[15:52:48 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[15:52:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:52:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[15:52:48 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[15:52:48 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:829)
[15:52:48 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:328)
[15:52:48 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:519)
[15:52:48 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:474)
[15:52:48 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[15:52:48 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[15:52:48 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[15:52:48 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[15:52:48 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[15:52:48 WARN]:        at NPCDestinationsRancher-2_5_0.jar//net.livecar.nuttyworks.destinations_rancher.plugin.Rancher_Commands.npcDest_locRancher(Rancher_Commands.java:45)
[15:52:48 WARN]:        ... 28 more

**Comment by Nutty101** [comment]
Rancher is not supported anymore. If the commands are failing it's cause you are on a version that rancher does not work with.
